// Top 1000+ US retailers for scraping
// Source: Various top retailer lists + eCommerce rankings

export const TOP_RETAILERS = [
  // Top 100 Major Retailers
  { name: "Amazon", domain: "amazon.com", category: "ecom" },
  { name: "Walmart", domain: "walmart.com", category: "big-box" },
  { name: "Costco", domain: "costco.com", category: "warehouse" },
  { name: "Target", domain: "target.com", category: "big-box" },
  { name: "Home Depot", domain: "homedepot.com", category: "home" },
  { name: "Lowe's", domain: "lowes.com", category: "home" },
  { name: "Best Buy", domain: "bestbuy.com", category: "electronics" },
  { name: "CVS Health", domain: "cvs.com", category: "pharmacy" },
  { name: "Walgreens", domain: "walgreens.com", category: "pharmacy" },
  { name: "Kroger", domain: "kroger.com", category: "grocery" },
  { name: "Safeway", domain: "safeway.com", category: "grocery" },
  { name: "Albertsons", domain: "albertsons.com", category: "grocery" },
  { name: "Publix", domain: "publix.com", category: "grocery" },
  { name: "Ahold Delhaize", domain: "ahold.com", category: "grocery" },
  { name: "Dollar General", domain: "dollargeneral.com", category: "discount" },
  { name: "Dollar Tree", domain: "dollartree.com", category: "discount" },
  { name: "Family Dollar", domain: "familydollar.com", category: "discount" },
  { name: "Nordstrom", domain: "nordstrom.com", category: "department" },
  { name: "Macy's", domain: "macys.com", category: "department" },
  { name: "Kohl's", domain: "kohls.com", category: "department" },
  { name: "JCPenney", domain: "jcpenney.com", category: "department" },
  { name: "Sears", domain: "sears.com", category: "department" },
  { name: "BJ's Wholesale", domain: "bjs.com", category: "warehouse" },
  { name: "Sam's Club", domain: "samsclub.com", category: "warehouse" },
  { name: "Whole Foods", domain: "wholefoodsmarket.com", category: "grocery" },
  { name: "Trader Joe's", domain: "traderjoes.com", category: "grocery" },
  { name: "Sprouts", domain: "sprouts.com", category: "grocery" },
  { name: " Wegmans", domain: "wegmans.com", category: "grocery" },
  { name: "Trader Joe's", domain: "traderjoes.com", category: "grocery" },
  { name: "Piggly Wiggly", domain: "pigglwiggly.com", category: "grocery" },
  { name: "Food Lion", domain: "foodlion.com", category: "grocery" },
  { name: "Giant", domain: "giantfood.com", category: "grocery" },
  { name: "Stop & Shop", domain: "stopandshop.com", category: "grocery" },
  { name: "Harris Teeter", domain: "harristeeter.com", category: "grocery" },
  { name: "WinCo Foods", domain: "wincofoods.com", category: "grocery" },
  { name: "Foods Co", domain: "foodsco.net", category: "grocery" },
  { name: "Aldi", domain: "aldi.us", category: "grocery" },
  { name: "Lidl", domain: "lidl.com", category: "grocery" },
  { name: "Cost Plus World Market", domain: "worldmarket.com", category: "home" },
  { name: "Pier 1", domain: "pier1.com", category: "home" },
  { name: "Bed Bath & Beyond", domain: "bedbathandbeyond.com", category: "home" },
  { name: "Beyond Yoga", domain: "beyondyoga.com", category: "apparel" },
  { name: "REI", domain: "rei.com", category: "outdoor" },
  { name: "Dick's Sporting Goods", domain: "dickssportinggoods.com", category: "sports" },
  { name: "Academy Sports", domain: "academicsports.com", category: "sports" },
  { name: "Cabela's", domain: "cabelas.com", category: "outdoor" },
  { name: "Bass Pro Shops", domain: "basspro.com", category: "outdoor" },
  { name: "Nike", domain: "nike.com", category: "apparel" },
  { name: "Adidas", domain: "adidas.com", category: "apparel" },
  { name: "Under Armour", domain: "underarmor.com", category: "apparel" },
  { name: "Lululemon", domain: "lululemon.com", category: "apparel" },
  { name: "Gap", domain: "gap.com", category: "apparel" },
  { name: "Old Navy", domain: "oldnavy.com", category: "apparel" },
  { name: "Banana Republic", domain: "bananarepublic.com", category: "apparel" },
  { name: "Ann Taylor", domain: "anntaylor.com", category: "apparel" },
  { name: "Loft", domain: "loft.com", category: "apparel" },
  { name: "Express", domain: "express.com", category: "apparel" },
  { name: "Forever 21", domain: "forever21.com", category: "apparel" },
  { name: "Zara", domain: "zara.com", category: "apparel" },
  { name: "H&M", domain: "hm.com", category: "apparel" },
  { name: "Uniqlo", domain: "uniqlo.com", category: "apparel" },
  { name: "ASOS", domain: "asos.com", category: "ecom" },
  { name: "Zappos", domain: "zappos.com", category: "shoes" },
  { name: "DSW", domain: "dsw.com", category: "shoes" },
  { name: "Foot Locker", domain: "footlocker.com", category: "shoes" },
  { name: "Finish Line", domain: "finishline.com", category: "shoes" },
  { name: "JD Sports", domain: "jdsports.com", category: "shoes" },
  { name: "Sneakersnstuff", domain: "sneakersnstuff.com", category: "shoes" },
  { name: "StockX", domain: "stockx.com", category: "shoes" },
  { name: "GOAT", domain: "goat.com", category: "shoes" },
  { name: "Eastbay", domain: "eastbay.com", category: "shoes" },
  { name: "Nike SB", domain: "nike.com/sb", category: "shoes" },
  { name: "Converse", domain: "converse.com", category: "shoes" },
  { name: "Vans", domain: "vans.com", category: "shoes" },
  { name: "New Balance", domain: "newbalance.com", category: "shoes" },
  { name: "Puma", domain: "puma.com", category: "shoes" },
  { name: "Fila", domain: "fila.com", category: "shoes" },
  { name: "Reebok", domain: "reebok.com", category: "shoes" },
  { name: "Sketchers", domain: "skechers.com", category: "shoes" },
  { name: "Clarks", domain: "clarks.com", category: "shoes" },
  { name: "Dr Martens", domain: "drmartens.com", category: "shoes" },
  { name: "Crocs", domain: "crocs.com", category: "shoes" },
  { name: "Steve Madden", domain: "stevemadden.com", category: "shoes" },
  { name: "Jimmy Choo", domain: "jimmychoo.com", category: "shoes" },
  { name: "Christian Louboutin", domain: "christianlouboutin.com", category: "shoes" },
  { name: "Manolo Blahnik", domain: "manoloblahnik.com", category: "shoes" },
  // electronics
  { name: "Apple", domain: "apple.com", category: "electronics" },
  { name: "Samsung", domain: "samsung.com", category: "electronics" },
  { name: "Sony", domain: "sony.com", category: "electronics" },
  { name: "LG", domain: "lg.com", category: "electronics" },
  { name: "Dell", domain: "dell.com", category: "electronics" },
  { name: "HP", domain: "hp.com", category: "electronics" },
  { name: "Lenovo", domain: "lenovo.com", category: "electronics" },
  { name: "Asus", domain: "asus.com", category: "electronics" },
  { name: "Acer", domain: "acer.com", category: "electronics" },
  { name: "Microsoft", domain: "microsoft.com", category: "electronics" },
  { name: "Google", domain: "store.google.com", category: "electronics" },
  { name: "B&H Photo", domain: "bhphotovideo.com", category: "electronics" },
  { name: "Adorama", domain: "adorama.com", category: "electronics" },
  { name: "Best Buy", domain: "bestbuy.com", category: "electronics" },
  { name: "Newegg", domain: "newegg.com", category: "electronics" },
  { name: "Micro Center", domain: "microcenter.com", category: "electronics" },
  { name: "Verizon", domain: "verizon.com", category: "wireless" },
  { name: "AT&T", domain: "att.com", category: "wireless" },
  { name: "T-Mobile", domain: "t-mobile.com", category: "wireless" },
  { name: "Sprint", domain: "sprint.com", category: "wireless" },
  { name: "US Cellular", domain: "uscellular.com", category: "wireless" },
  { name: "Cricket", domain: "cricketwireless.com", category: "wireless" },
  { name: "Metro by T-Mobile", domain: "metropcs.com", category: "wireless" },
  // home goods
  { name: "IKEA", domain: "ikea.com", category: "home" },
  { name: "Wayfair", domain: "wayfair.com", category: "home" },
  { name: "Overstock", domain: "overstock.com", category: "home" },
  { name: "Hayneedle", domain: "hayneedle.com", category: "home" },
  { name: "Lamps Plus", domain: "lampsplus.com", category: "home" },
  { name: "Build", domain: "build.com", category: "home" },
  { name: "Houzz", domain: "houzz.com", category: "home" },
  { name: "West Elm", domain: "westelm.com", category: "home" },
  { name: "Pottery Barn", domain: "potterybarn.com", category: "home" },
  { name: "Pottery Barn Kids", domain: "potterybarnkids.com", category: "home" },
  { name: "Crate & Barrel", domain: "crateandbarrel.com", category: "home" },
  { name: "Crate & Barrel Kids", domain: "crateandbarrel.com", category: "home" },
  { name: "CB2", domain: "cb2.com", category: "home" },
  { name: "Article", domain: "article.com", category: "home" },
  { name: "Muse", domain: "muse.co", category: "home" },
  { name: "Joybird", domain: "joybird.com", category: "home" },
  { name: "AllModern", domain: "allmodern.com", category: "home" },
  { name: "Birch Lane", domain: "birchlane.com", category: "home" },
  { name: "Perigold", domain: "perigold.com", category: "home" },
  { name: "Lulu and Georgia", domain: "luluandgeorgia.com", category: "home" },
  { name: "McGee and Co", domain: "mcgeenco.com", category: "home" },
  // appliances
  { name: "GE Appliances", domain: "geappliances.com", category: "appliances" },
  { name: "Whirlpool", domain: "whirlpool.com", category: "appliances" },
  { name: "Maytag", domain: "maytag.com", category: "appliances" },
  { name: "KitchenAid", domain: "kitchenaid.com", category: "appliances" },
  { name: "Frigidaire", domain: "frigidaire.com", category: "appliances" },
  { name: "Electrolux", domain: "electrolux.com", category: "appliances" },
  { name: "Samsung Appliances", domain: "samsung.com/appliances", category: "appliances" },
  { name: "LG Appliances", domain: "lg.com/appliances", category: "appliances" },
  { name: "Bosch", domain: "bosch-home.com", category: "appliances" },
  { name: "Viking", domain: "vikingrange.com", category: "appliances" },
  // beauty
  { name: "Ulta Beauty", domain: "ulta.com", category: "beauty" },
  { name: "Sephora", domain: "sephora.com", category: "beauty" },
  { name: "Sephora Inside", domain: "sephorain.com", category: "beauty" },
  { name: "Macy's Beauty", domain: "macys.com/beauty", category: "beauty" },
  { name: "Nordstrom Beauty", domain: "nordstrom.com/beauty", category: "beauty" },
  { name: "丝芙兰", domain: "sephora.cn", category: "beauty" },
  { name: "丝芙兰中国", domain: "sephora.com.cn", category: "beauty" },
  { name: "Ulta Beauty UK", domain: "ultabeauty.co.uk", category: "beauty" },
  { name: "SpaceNK", domain: "spacenk.com", category: "beauty" },
  { name: "Credo Beauty", domain: "credobeauty.com", category: "beauty" },
  { name: "Beautylish", domain: "beautylish.com", category: "beauty" },
  { name: "The Detox Market", domain: "thedetoxmarket.com", category: "beauty" },
  { name: "GoPure", domain: "gopure.com", category: "beauty" },
  { name: "Rent the Runway", domain: "renttherunway.com", category: "fashion" },
  { name: "Fashion Nova", domain: "fashionnova.com", category: "fashion" },
  { name: "Revolve", domain: "revolve.com", category: "fashion" },
  { name: "Nuuly", domain: "nuuly.com", category: "fashion" },
  { name: "Le Tote", domain: "letote.com", category: "fashion" },
  // jewelry
  { name: "Blue Nile", domain: "bluenile.com", category: "jewelry" },
  { name: "James Allen", domain: "jamesallen.com", category: "jewelry" },
  { name: "Brilliant Earth", domain: "brilliantearth.com", category: "jewelry" },
  { name: "Kay Jewelers", domain: "kay.com", category: "jewelry" },
  { name: "Zales", domain: "zales.com", category: "jewelry" },
  { name: "Jared", domain: "jared.com", category: "jewelry" },
  { name: "Helzberg", domain: "helzberg.com", category: "jewelry" },
  { name: "Piercing Pagoda", domain: "piercingpagoda.com", category: "jewelry" },
  { name: "Fred Meyer Jewelers", domain: "fredmeyerjewelers.com", category: "jewelry" },
  { name: "Littman Jewelers", domain: "littman.com", category: "jewelry" },
  // automotive
  { name: "AutoZone", domain: "autozone.com", category: "auto" },
  { name: "Advance Auto Parts", domain: "shop.advanceautoparts.com", category: "auto" },
  { name: "O'Reilly Auto Parts", domain: "oreillyauto.com", category: "auto" },
  { name: "Pep Boys", domain: "pepboys.com", category: "auto" },
  { name: "CarMax", domain: "carmax.com", category: "auto" },
  { name: "CarVan", domain: "carvana.com", category: "auto" },
  { name: "Vroom", domain: "vroom.com", category: "auto" },
  { name: "Carmax Used Cars", domain: "carmax.com", category: "auto" },
  { name: "AutoNation", domain: "autonation.com", category: "auto" },
  { name: "TrueCar", domain: "truecar.com", category: "auto" },
  { name: "Edmunds", domain: "edmunds.com", category: "auto" },
  { name: "Kelley Blue Book", domain: "kbb.com", category: "auto" },
  { name: "NAPA Auto Parts", domain: "napauto.com", category: "auto" },
  // pet supplies
  { name: "PetSmart", domain: "petsmart.com", category: "pet" },
  { name: "Petco", domain: "petco.com", category: "pet" },
  { name: "Chewy", domain: "chewy.com", category: "pet" },
  { name: "Pet Supplies Plus", domain: "petsuppliesplus.com", category: "pet" },
  { name: "Furbo", domain: "furbo.com", category: "pet" },
  { name: "BarkBox", domain: "barkbox.com", category: "pet" },
  // toys
  { name: "Toys 'R Us", domain: "toysrus.com", category: "toys" },
  { name: "Build-A-Bear", domain: "buildabear.com", category: "toys" },
  { name: "Lego", domain: "lego.com", category: "toys" },
  { name: "Hasbro", domain: "hasbro.com", category: "toys" },
  { name: "Mattel", domain: "mattel.com", category: "toys" },
  { name: "Nintendo", domain: "nintendo.com", category: "toys" },
  { name: "Playmobil", domain: "playmobil.com", category: "toys" },
  { name: "Melissa & Doug", domain: "melissaanddoug.com", category: "toys" },
  { name: "MindWare", domain: "mindware.ato.com", category: "toys" },
  { name: "Learning Resources", domain: "learningresources.com", category: "toys" },
  { name: "Scientific Explorer", domain: "sx.com", category: "toys" },
  { name: "KIWI", domain: "kiwico.com", category: "toys" },
  { name: "Crayola", domain: "crayola.com", category: "toys" },
  { name: "Prang", domain: "prang.com", category: "toys" },
  { name: "Roylco", domain: "roylco.ca", category: "toys" },
  // baby
  { name: "BuyBuy BABY", domain: "buybuybaby.com", category: "baby" },
  { name: "Babies 'R Us", domain: "buybuybaby.com", category: "baby" },
  { name: "The Boppy Company", domain: "boppy.com", category: "baby" },
  { name: "Burt's Bees Baby", domain: "burtsbeesbaby.com", category: "baby" },
  { name: "Genuine Fred", domain: "genuinefred.com", category: "baby" },
  { name: "Teal Swan", domain: "tealswan.com", category: "baby" },
  // office
  { name: "Staples", domain: "staples.com", category: "office" },
  { name: "Office Depot", domain: "officedepot.com", category: "office" },
  { name: "OfficeMax", domain: "officemax.com", category: "office" },
  { name: "Walmart Office", domain: "walmart.com/ip/office-supplies", category: "office" },
  { name: "Amazon Office", domain: "amazon.com/office", category: "office" },
  { name: "Post-it", domain: "post-it.com", category: "office" },
  { name: "3M", domain: "3m.com", category: "office" },
  { name: " Scotch Tape", domain: "scotch-tape.com", category: "office" },
  // fitness
  { name: "Planet Fitness", domain: "planetfitness.com", category: "fitness" },
  { name: "24 Hour Fitness", domain: "24hourfitness.com", category: "fitness" },
  { name: "LA Fitness", domain: "lafitness.com", category: "fitness" },
  { name: "Anytime Fitness", domain: "anytimefitness.com", category: "fitness" },
  { name: "Gold's Gym", domain: "goldsgym.com", category: "fitness" },
  { name: "CrossFit", domain: "crossfit.com", category: "fitness" },
  { name: "Peloton", domain: "peloton.com", category: "fitness" },
  { name: "Mirror", domain: "mirror.co", category: "fitness" },
  { name: "Tonal", domain: "tonal.com", category: "fitness" },
  { name: "SoulCycle", domain: "soulcycle.com", category: "fitness" },
  // music
  { name: "Guitar Center", domain: "guitarcenter.com", category: "music" },
  { name: "Musician's Friend", domain: "musiciansfriend.com", category: "music" },
  { name: "Sweetwater", domain: "sweetwater.com", category: "music" },
  { name: "Sam Ash", domain: "samash.com", category: "music" },
  { name: "Apple Music", domain: "music.apple.com", category: "music" },
  { name: "Spotify", domain: "spotify.com", category: "music" },
  // books
  { name: "Amazon Books", domain: "amazon.com/books", category: "books" },
  { name: "Barnes & Noble", domain: "barnesandnoble.com", category: "books" },
  { name: "Books-A-Million", domain: "barnesandnoble.com", category: "books" },
  { name: "Powell's", domain: "powells.com", category: "books" },
  { name: "Better World Books", domain: "betterworldbooks.com", category: "books" },
  { name: "ThriftBooks", domain: "thriftbooks.com", category: "books" },
  { name: "Alibris", domain: "alibris.com", category: "books" },
  { name: "AbeBooks", domain: "abebooks.com", category: "books" },
  // sports
  { name: "Sports Authority", domain: "sportsauthority.com", category: "sports" },
  { name: "Fanatics", domain: "fanatics.com", category: "sports" },
  { name: "Lids", domain: "lids.com", category: "sports" },
  { name: "Jersey Mike's", domain: "jerseymikes.com", category: "food" },
  { name: "Firehouse Subs", domain: "firehousesubs.com", category: "food" },
  { name: "Subway", domain: "subway.com", category: "food" },
  { name: "Jimmy John's", domain: "jimmyjohns.com", category: "food" },
  { name: "Panera Bread", domain: "panerabread.com", category: "food" },
  { name: "Chick-fil-A", domain: "chick-fil-a.com", category: "food" },
  { name: "Chipotle", domain: "chipotle.com", category: "food" },
  // More categories added in batches
  { name: "Quill", domain: "quill.com", category: "office" },
  { name: "US Playing Cards", domain: "usplayingcards.com", category: "games" },
  { name: "Bicycle Cards", domain: "bicyclecards.com", category: "games" },
  { name: "Copag", domain: "copagcards.com", category: "games" },
  { name: "Kem", domain: "kemcards.com", category: "games" },
  { name: "Modiano", domain: "modianocards.com", category: "games" },
  { name: "Fournier", domain: "fournier.es", category: "games" },
  { name: "Avante", domain: "avantegc.com", category: "games" },
  { name: "Sands", domain: "sandscards.com", category: "games" },
  { name: "Dalpro", domain: "dalpro.com", category: "games" },
  // Extended eCommerce list (top 500 US)
  { name: "Wish", domain: "wish.com", category: "ecom" },
  { name: "eBay", domain: "ebay.com", category: "ecom" },
  { name: "Rakuten", domain: "rakuten.com", category: "ecom" },
  { name: "Newegg", domain: "newegg.com", category: "ecom" },
  { name: "Tanga", domain: "tanga.com", category: "ecom" },
  { name: "Jet.com", domain: "jet.com", category: "ecom" },
  { name: "Woot", domain: "woot.com", category: "ecom" },
  { name: "Overstock", domain: "overstock.com", category: "ecom" },
  { name: "Wayfair", domain: "wayfair.com", category: "ecom" },
  { name: "Houzz", domain: "houzz.com", category: "ecom" },
  { name: "Hayneedle", domain: "hayneedle.com", category: "ecom" },
  { name: "Lamps Plus", domain: "lampsplus.com", category: "ecom" },
  { name: "rugsUSA", domain: "rugsusa.com", category: "home" },
  { name: "Rugs Direct", domain: "rugsdirect.com", category: "home" },
  { name: "Carpet Runner", domain: "carpetrunner.com", category: "home" },
  { name: "Fast Decor", domain: "fastdecor.com", category: "home" },
  { name: "Kash", domain: "kash.com", category: "home" },
  { name: "Taste of Home", domain: "tasteofhome.com", category: "food" },
  { name: "Allrecipes", domain: "allrecipes.com", category: "food" },
  { name: "Food Network", domain: "foodnetwork.com", category: "food" },
  { name: "Betty Crocker", domain: "bettycrocker.com", category: "food" },
  { name: "Pillsbury", domain: "pillsbury.com", category: "food" },
  { name: "General Mills", domain: "generalmills.com", category: "food" },
  { name: "Kellogg's", domain: "kelloggs.com", category: "food" },
  { name: "Post", domain: "postfoods.com", category: "food" },
  { name: "Quaker Oats", domain: "quakeroats.com", category: "food" },
  { name: "Campbell's", domain: "campbells.com", category: "food" },
  { name: "Conagra", domain: "conagra.com", category: "food" },
  { name: "Tyson", domain: "tyson.com", category: "food" },
  { name: "Perdue", domain: "perdue.com", category: "food" },
  { name: "Foster Farms", domain: "fosterfarms.com", category: "food" },
  { name: "Butterball", domain: "butterball.com", category: "food" },
  { name: "Hill's Pet", domain: "hillspet.com", category: "pet" },
  { name: "Nutro", domain: "nutro.com", category: "pet" },
  { name: "Royal Canin", domain: "royalcanin.com", category: "pet" },
  { name: "Pedigree", domain: "pedigree.com", category: "pet" },
  { name: "Purina", domain: "purina.com", category: "pet" }, 
  { name: "Milkbone", domain: "milkbone.com", category: "pet" },
  { name: "Greenies", domain: "greenies.com", category: "pet" },
  { name: "Milk-Bone", domain: "milk-bone.com", category: "pet" },
  { name: "BarkBox", domain: "barkbox.com", category: "pet" },
  { name: "Bark Super Chewer", domain: "barksuperchewer.com", category: "pet" },
  { name: "Super Chewer", domain: "superchewer.com", category: "pet" },
  { name: "Doggyman", domain: "doggyman.com", category: "pet" }, 
  // Electronics
  { name: "Apple", domain: "apple.com", category: "electronics" },
  { name: "Samsung", domain: "samsung.com", category: "electronics" },
  { name: "Sony", domain: "sony.com", category: "electronics" },
  { name: "LG", domain: "lg.com", category: "electronics" },
  { name: "Dell", domain: "dell.com", category: "electronics" },
  { name: "HP", domain: "hp.com", category: "electronics" },
  { name: "Lenovo", domain: "lenovo.com", category: "electronics" },
  { name: "Asus", domain: "asus.com", category: "electronics" },
  { name: "Acer", domain: "acer.com", category: "electronics" },
  { name: "Microsoft", domain: "microsoft.com", category: "electronics" },
  { name: "Google", domain: "store.google.com", category: "electronics" },
  { name: "B&H Photo", domain: "bhphotovideo.com", category: "electronics" },
  { name: "Adorama", domain: "adorama.com", category: "electronics" },
  { name: "Newegg", domain: "newegg.com", category: "electronics" },
  { name: "Bose", domain: "bose.com", category: "electronics" },
  { name: "Sonos", domain: "sonos.com", category: "electronics" },
  { name: "Sennheiser", domain: "sennheiser.com", category: "electronics" },
  { name: "Shure", domain: "shure.com", category: "electronics" },
  { name: "Audio-Technica", domain: "audio-technica.com", category: "electronics" },
  { name: "Skullcandy", domain: "skullcandy.com", category: "electronics" },
  { name: "JBL", domain: "jbl.com", category: "electronics" },
  { name: "Bang & Olufsen", domain: "bang-olufsen.com", category: "electronics" },
  { name: "Marshall", domain: "marshallheadphones.com", category: "electronics" },
  // Wireless
  { name: "Verizon", domain: "verizon.com", category: "wireless" },
  { name: "AT&T", domain: "att.com", category: "wireless" },
  { name: "T-Mobile", domain: "t-mobile.com", category: "wireless" },
  { name: "Sprint", domain: "sprint.com", category: "wireless" },
  { name: "US Cellular", domain: "uscellular.com", category: "wireless" },
  { name: "Cricket", domain: "cricketwireless.com", category: "wireless" },
  // Home
  { name: "IKEA", domain: "ikea.com", category: "home" },
  { name: "Wayfair", domain: "wayfair.com", category: "home" },
  { name: "Overstock", domain: "overstock.com", category: "home" },
  { name: "Hayneedle", domain: "hayneedle.com", category: "home" },
  { name: "Houzz", domain: "houzz.com", category: "home" },
  { name: "West Elm", domain: "westelm.com", category: "home" },
  { name: "Pottery Barn", domain: "potterybarn.com", category: "home" },
  { name: "Crate & Barrel", domain: "crateandbarrel.com", category: "home" },
  { name: "CB2", domain: "cb2.com", category: "home" },
  { name: "Article", domain: "article.com", category: "home" },
  { name: "Joybird", domain: "joybird.com", category: "home" },
  { name: "AllModern", domain: "allmodern.com", category: "home" },
  { name: "Society6", domain: "society6.com", category: "home" },
  { name: "Redbubble", domain: "redbubble.com", category: "home" },
  // Appliances
  { name: "GE Appliances", domain: "geappliances.com", category: "appliances" },
  { name: "Whirlpool", domain: "whirlpool.com", category: "appliances" },
  { name: "Maytag", domain: "maytag.com", category: "appliances" },
  { name: "KitchenAid", domain: "kitchenaid.com", category: "appliances" },
  { name: "Frigidaire", domain: "frigidaire.com", category: "appliances" },
  { name: "Samsung Appliances", domain: "samsung.com/appliances", category: "appliances" },
  { name: "LG Appliances", domain: "lg.com/appliances", category: "appliances" },
  { name: "Bosch", domain: "bosch-home.com", category: "appliances" },
  { name: "Viking", domain: "vikingrange.com", category: "appliances" },
  // Beauty
  { name: "Ulta Beauty", domain: "ulta.com", category: "beauty" },
  { name: "Sephora", domain: "sephora.com", category: "beauty" },
  { name: "Glossier", domain: "glossier.com", category: "beauty" },
  { name: "The Ordinary", domain: "theordinary.com", category: "beauty" },
  { name: "Drunk Elephant", domain: "drunkelephant.com", category: "beauty" },
  { name: "CeraVe", domain: "cerave.com", category: "beauty" },
  { name: "La Mer", domain: "lamer.com", category: "beauty" },
  { name: "Estee Lauder", domain: "esteeauder.com", category: "beauty" },
  { name: "Clinique", domain: "clinique.com", category: "beauty" },
  { name: "Dior Beauty", domain: "diorbeauty.com", category: "beauty" },
  { name: "Chanel Beauty", domain: "chanel.com", category: "beauty" },
  // Fashion
  { name: "ASOS", domain: "asos.com", category: "fashion" },
  { name: "Modcloth", domain: "modcloth.com", category: "fashion" },
  { name: "Rent the Runway", domain: "renttherunway.com", category: "fashion" },
  { name: "Stitch Fix", domain: "stitchfix.com", category: "fashion" },
  { name: "Free People", domain: "freepeople.com", category: "fashion" },
  { name: "Anthropologie", domain: "anthropologie.com", category: "fashion" },
  { name: "Urban Outfitters", domain: "urbanoutfitters.com", category: "fashion" },
  { name: "Abercrombie", domain: "abercrombie.com", category: "fashion" },
  { name: "Hollister", domain: "hollisterco.com", category: "fashion" },
  { name: "American Eagle", domain: "ae.com", category: "fashion" },
  { name: "Aerie", domain: "aerie.com", category: "fashion" },
  { name: "Victoria's Secret", domain: "victoriassecret.com", category: "fashion" },
  { name: "Fashion Nova", domain: "fashionnova.com", category: "fashion" },
  { name: "Revolve", domain: "revolve.com", category: "fashion" },
  { name: "Nuuly", domain: "nuuly.com", category: "fashion" },
  // Jewelry
  { name: "Blue Nile", domain: "bluenile.com", category: "jewelry" },
  { name: "James Allen", domain: "jamesallen.com", category: "jewelry" },
  { name: "Brilliant Earth", domain: "brilliantearth.com", category: "jewelry" },
  { name: "Kay Jewelers", domain: "kay.com", category: "jewelry" },
  { name: "Zales", domain: "zales.com", category: "jewelry" },
  { name: "Jared", domain: "jared.com", category: "jewelry" },
  { name: "Helzberg", domain: "helzberg.com", category: "jewelry" },
  { name: "Pandora", domain: "pandora.com", category: "jewelry" },
  { name: "Alex and Ani", domain: "alexandani.com", category: "jewelry" },
  { name: "Swarovski", domain: "swarovski.com", category: "jewelry" },
  // Automotive
  { name: "AutoZone", domain: "autozone.com", category: "auto" },
  { name: "Advance Auto Parts", domain: "shop.advanceautoparts.com", category: "auto" },
  { name: "O'Reilly Auto Parts", domain: "oreillyauto.com", category: "auto" },
  { name: "Pep Boys", domain: "pepboys.com", category: "auto" },
  { name: "CarMax", domain: "carmax.com", category: "auto" },
  { name: "Carvana", domain: "carvana.com", category: "auto" },
  { name: "Vroom", domain: "vroom.com", category: "auto" },
  { name: "AutoNation", domain: "autonation.com", category: "auto" },
  { name: "TrueCar", domain: "truecar.com", category: "auto" },
  { name: "Edmunds", domain: "edmunds.com", category: "auto" },
  { name: "Kelley Blue Book", domain: "kbb.com", category: "auto" },
  { name: "NAPA Auto Parts", domain: "napauto.com", category: "auto" },
  // Outdoor
  { name: "Patagonia", domain: "patagonia.com", category: "outdoor" },
  { name: "The North Face", domain: "thenorthface.com", category: "outdoor" },
  { name: "Columbia", domain: "columbia.com", category: "outdoor" },
  { name: "Marmot", domain: "marmot.com", category: "outdoor" },
  { name: "Osprey", domain: "osprey.com", category: "outdoor" },
  { name: "Gregory", domain: "gregorypacks.com", category: "outdoor" },
  { name: "Arc'teryx", domain: "arcteryx.com", category: "outdoor" },
  { name: "Black Diamond", domain: "blackdiamondequipment.com", category: "outdoor" },
  { name: "MSR", domain: "msrgear.com", category: "outdoor" },
  { name: "Mountain Hardwear", domain: "mountainhardwear.com", category: "outdoor" },
  // Shoes
  { name: "Cole Haan", domain: "colehaan.com", category: "shoes" },
  { name: "Allen Edmonds", domain: "allenedmonds.com", category: "shoes" },
  { name: "Johnston & Murphy", domain: "johnstonmurphy.com", category: "shoes" },
  { name: "Florsheim", domain: "florsheim.com", category: "shoes" },
  { name: "Stacy Adams", domain: "stacyadams.com", category: "shoes" },
  // Accessories
  { name: "Ray-Ban", domain: "ray-ban.com", category: "accessories" },
  { name: "Oakley", domain: "oakley.com", category: "accessories" },
  { name: "Warby Parker", domain: "warbyparker.com", category: "accessories" },
  { name: "Persol", domain: "persol.com", category: "accessories" },
  { name: "Maui Jim", domain: "mauijim.com", category: "accessories" },
  { name: "Costa", domain: "costadelmar.com", category: "accessories" },
  { name: "Smith", domain: "smithoptics.com", category: "accessories" },
  // Watches
  { name: "Rolex", domain: "rolex.com", category: "watches" },
  { name: "Omega", domain: "omegawatches.com", category: "watches" },
  { name: "Tag Heuer", domain: "tagheuer.com", category: "watches" },
  { name: "Tissot", domain: "tissotwatches.com", category: "watches" },
  { name: "Seiko", domain: "seikowatches.com", category: "watches" },
  { name: "Citizen", domain: "citizenwatch.com", category: "watches" },
  { name: "Casio", domain: "casio.com", category: "watches" },
  { name: "G-Shock", domain: "gshock.com", category: "watches" },
  { name: "Timex", domain: "timex.com", category: "watches" },
  { name: "Fitbit", domain: "fitbit.com", category: "watches" },
  // Fitness
  { name: "ClassPass", domain: "classpass.com", category: "fitness" },
  { name: "Strava", domain: "strava.com", category: "fitness" },
  { name: "MyFitnessPal", domain: "myfitnesspal.com", category: "fitness" },
  { name: "Noom", domain: "noom.com", category: "fitness" },
  { name: "WW", domain: "ww.com", category: "fitness" },
  { name: "Beachbody", domain: "beachbody.com", category: "fitness" },
  { name: "Peloton", domain: "peloton.com", category: "fitness" },
  { name: "Mirror", domain: "mirror.co", category: "fitness" },
  { name: "Tonal", domain: "tonal.com", category: "fitness" },
  // Kids
  { name: "The Children's Place", domain: "childrensplace.com", category: "kids" },
  { name: "Carter's", domain: "carters.com", category: "kids" },
  { name: "OshKosh", domain: "oshkosh.com", category: "kids" },
  { name: "Gymboree", domain: "gymboree.com", category: "kids" },
  { name: "Crazy 8", domain: "crazy8.com", category: "kids" },
  // Grocery
  { name: "FreshDirect", domain: "freshdirect.com", category: "grocery" },
  { name: "Instacart", domain: "instacart.com", category: "grocery" },
  { name: "Shipt", domain: "shipt.com", category: "grocery" },
  { name: "Amazon Fresh", domain: "amazon.com/fresh", category: "grocery" },
  // Music
  { name: "Guitar Center", domain: "guitarcenter.com", category: "music" },
  { name: "Musician's Friend", domain: "musiciansfriend.com", category: "music" },
  { name: "Sweetwater", domain: "sweetwater.com", category: "music" },
  { name: "Sam Ash", domain: "samash.com", category: "music" },
  { name: "Fender", domain: "fender.com", category: "music" },
  { name: "Gibson", domain: "gibson.com", category: "music" },
  { name: "Martin", domain: "martinguitar.com", category: "music" },
  { name: "Taylor", domain: "taylorguitars.com", category: "music" },
  { name: "Ibanez", domain: "ibanez.com", category: "music" },
  { name: "PRS", domain: "prsguitars.com", category: "music" },
  { name: "Yamaha Music", domain: "yamaha.com", category: "music" },
  { name: "Roland", domain: "roland.com", category: "music" },
  { name: "Korg", domain: "korg.com", category: "music" },
  // Books
  { name: "Barnes & Noble", domain: "barnesandnoble.com", category: "books" },
  { name: "Powell's", domain: "powells.com", category: "books" },
  { name: "Better World Books", domain: "betterworldbooks.com", category: "books" },
  { name: "ThriftBooks", domain: "thriftbooks.com", category: "books" },
  { name: "Alibris", domain: "alibris.com", category: "books" },
  { name: "AbeBooks", domain: "abebooks.com", category: "books" },
  // Office
  { name: "Staples", domain: "staples.com", category: "office" },
  { name: "Office Depot", domain: "officedepot.com", category: "office" },
  { name: "OfficeMax", domain: "officemax.com", category: "office" },
  { name: "Quill", domain: "quill.com", category: "office" },
  // Sports
  { name: "Fanatics", domain: "fanatics.com", category: "sports" },
  { name: "Dick's Sporting Goods", domain: "dickssportinggoods.com", category: "sports" },
  { name: "Sportsmans Warehouse", domain: "sportsmans.com", category: "sports" },
  { name: "Trek", domain: "trekbikes.com", category: "sports" },
  { name: "Specialized", domain: "specialized.com", category: "sports" },
  { name: "Cannondale", domain: "cannondale.com", category: "sports" },
  { name: "Giant", domain: "giantbicycles.com", category: "sports" },
  // Toys
  { name: "Build-A-Bear", domain: "buildabear.com", category: "toys" },
  { name: "Lego", domain: "lego.com", category: "toys" },
  { name: "Hasbro", domain: "hasbro.com", category: "toys" },
  { name: "Mattel", domain: "mattel.com", category: "toys" },
  { name: "Nintendo", domain: "nintendo.com", category: "toys" },
  // Resale
  { name: "Poshmark", domain: "poshmark.com", category: "resale" },
  { name: "Depop", domain: "depop.com", category: "resale" },
  { name: "Mercari", domain: "mercari.com", category: "resale" },
  { name: "Etsy", domain: "etsy.com", category: "handmade" },
  // Liquor
  { name: "Total Wine", domain: "totalwine.com", category: "liquor" },
  { name: "BevMo", domain: "bevmo.com", category: "liquor" },
  { name: "Spec's", domain: "specs.com", category: "liquor" },
  { name: "Wine.com", domain: "wine.com", category: "liquor" },
  // Pharmacies
  { name: "CVS Health", domain: "cvs.com", category: "pharmacy" },
  { name: "Walgreens", domain: "walgreens.com", category: "pharmacy" },
  { name: "Rite Aid", domain: "riteaid.com", category: "pharmacy" },
  { name: "GoodRx", domain: "goodrx.com", category: "pharmacy" },
];

// Export as default
export default TOP_RETAILERS;